SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET DATEFORMAT DMY;
SET DATEFIRST 7;
SET DEADLOCK_PRIORITY -8;
Select * from Cupones;



CREATE VIEW Cupones AS (
SELECT 
	SBA20.FECHA_CUPO AS [Fecha],
	STUFF(STUFF(RIGHT('000000' + CAST(SBA20.HORA_REC AS VARCHAR), 6), 5, 0, ':'), 3, 0, ':') AS [Hora],
    SBA20.T_COMP_REC AS [Tipo],
    SBA20.N_COMP_REC AS [Nro. comprobante],
    SBA22.COD_TARJET AS [Cód. tarjeta],
    SBA22.DESC_TARJE AS [Tarjeta],
    SBA20.LOTE AS [Nro. Lote],
    CAST(CAST(SBA20.N_CUPON AS INT) AS VARCHAR) AS [Nro. Cupón],
    CASE 
        WHEN SBA20.TIPO_CUPON = 'D' THEN SBA20.IMPORTE_TO * (-1)
        ELSE SBA20.IMPORTE_TO 
    END AS [Importe origen],
    CASE 
        WHEN SBA20.TIPO_CUPON = 'C' THEN 'Compra' 
        WHEN SBA20.TIPO_CUPON = 'D' THEN 'Devolución' 
        ELSE 'Anulado' 
    END AS [Tipo de cupón],
    SBA20.CANT_CUOTA AS [Cuotas],
    CASE 
        WHEN SBA20.ESTADO = 'D' THEN 'Depositado' 
        WHEN SBA20.ESTADO = 'C' THEN 'En cartera' 
        WHEN SBA20.ESTADO = 'A' THEN 'Acreditado' 
        WHEN SBA20.ESTADO = 'N' THEN 'Anulado' 
        WHEN SBA20.ESTADO = 'R' THEN 'Rechazado' 
    END AS [Estado],
    SUCURSAL.DESC_SUCURSAL AS [Sucursal]
FROM 
    SBA20
    LEFT JOIN CUOTA_CUPON ON 
        CUOTA_CUPON.ID_SBA22 = SBA20.ID_SBA22 AND 
        ISNULL(CUOTA_CUPON.ID_SUCURSAL, 0) = ISNULL(SBA20.ID_SUCURSAL, 0) AND 
        ISNULL(CUOTA_CUPON.ID_TERMINAL_POS, 0) = ISNULL(SBA20.ID_TERMINAL_POS, 0) AND 
        CUOTA_CUPON.LOTE = SBA20.LOTE AND 
        CUOTA_CUPON.N_CUPON = SBA20.N_CUPON AND 
        CUOTA_CUPON.CUOTA = SBA20.CUOTA AND 
        CUOTA_CUPON.FECHA_CUPON = SBA20.FECHA_CUPO
    LEFT JOIN SBA01 ON SBA20.COD_CTA = SBA01.COD_CTA
  --  LEFT JOIN MONEDA ON MONEDA.ID_MONEDA = SBA01.ID_MONEDA
  --  LEFT JOIN PARAMETRO_GBL ON MONEDA.ID_MONEDA = PARAMETRO_GBL.ID_MONEDA_ALTERNATIVA_HABITUAL
    LEFT JOIN SBA22 ON SBA22.ID_SBA22 = SBA20.ID_SBA22
    LEFT JOIN SUCURSAL ON 
        (SBA20.ID_SUCURSAL IS NULL AND 
        SUCURSAL.NRO_SUCURSAL = (
            SELECT SUC.NRO_SUCURSAL 
            FROM EMPRESA 
            JOIN SUCURSAL SUC ON EMPRESA.ID_SUCURSAL = SUC.ID_SUCURSAL
        )) OR 
        SBA20.ID_SUCURSAL = SUCURSAL.ID_SUCURSAL
 --   LEFT JOIN TERMINAL_POS ON ISNULL(TERMINAL_POS.ID_TERMINAL_POS, 0) = ISNULL(SBA20.ID_TERMINAL_POS, 0)
    LEFT JOIN PLAN_TARJETA ON SBA20.ID_PLAN_TARJETA = PLAN_TARJETA.ID_PLAN_TARJETA
    LEFT JOIN PROMOCION_TARJETA ON SBA20.ID_PROMOCION_TARJETA = PROMOCION_TARJETA.ID_PROMOCION_TARJETA
    LEFT JOIN SBA05 ON 
        SBA20.BARRA_REC = SBA05.BARRA AND 
        SBA20.T_COMP_REC = SBA05.COD_COMP AND 
        SBA20.N_COMP_REC = SBA05.N_COMP AND 
        SBA05.COD_CTA = SBA20.COD_CTA
  --  LEFT JOIN HOST ON SBA20.ID_HOST = HOST.ID_HOST
  --  LEFT JOIN EMPRESA ON 1 = 1
	LEFT JOIN GVA12 ON 
		GVA12.N_COMP = SBA05.N_COMP AND
		GVA12.T_COMP = SBA05.COD_COMP
	LEFT JOIN GVA43 ON
		GVA12.TALONARIO = GVA43.TALONARIO

WHERE GVA43.TIPO_TALONARIO = 'E'

GROUP BY 
    SBA22.COD_TARJET,
    SBA22.DESC_TARJE,
    SBA20.LOTE,
    SBA20.N_CUPON,
    SBA20.FECHA_CUPO,
    CASE 
        WHEN SBA20.TIPO_CUPON = 'D' THEN SBA20.IMPORTE_TO * (-1)
        ELSE SBA20.IMPORTE_TO 
    END,
    CASE 
        WHEN SBA20.TIPO_CUPON = 'C' THEN 'Compra' 
        WHEN SBA20.TIPO_CUPON = 'D' THEN 'Devolución' 
        ELSE 'Anulado' 
    END,
    SBA20.CANT_CUOTA,
    CASE 
        WHEN SBA20.ESTADO = 'D' THEN 'Depositado' 
        WHEN SBA20.ESTADO = 'C' THEN 'En cartera' 
        WHEN SBA20.ESTADO = 'A' THEN 'Acreditado' 
        WHEN SBA20.ESTADO = 'N' THEN 'Anulado' 
        WHEN SBA20.ESTADO = 'R' THEN 'Rechazado' 
    END,
    SUCURSAL.DESC_SUCURSAL,
    SBA20.T_COMP_REC,
    SBA20.N_COMP_REC,
	SBA20.HORA_REC
)