-- TABLA TEMPORAL PARA GRABACIÓN DEL CONCEPTO.
CREATE TABLE SBA04_TempConcepto (
    N_COMP VARCHAR(14),
    COD_COMP VARCHAR(10),
    ID_LEGAJO INT,
    TIPO_COD_RELACIONADO VARCHAR(1),
    CONCEPTO VARCHAR(40),
	ID_SBA02 INT
);
GO
