SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
SELECT 
	STA11.COD_ARTICU AS [CÓD. ARTÍCULO] ,
	STA11.DESCRIPCIO AS [DESCRIPCIÓN ARTÍCULO] ,
	STA11.PORC_UTILI AS [% DE UTILIDAD] ,
	GVA10.NRO_DE_LIS AS [CÓD. LISTA DE PRECIOS] ,
	GVA10.NOMBRE_LIS AS [NOMBRE LISTA DE PRECIOS] ,
	GVA17.PRECIO AS [PRECIO] ,
	CAST (GVA17.FECHA_MODI AS date) AS [FECHA DE ÚLTIMA MODIFICACIÓN] 
FROM 
 GVA17 (NOLOCK)  INNER JOIN GVA10 (NOLOCK) ON GVA10.NRO_DE_LIS = GVA17.NRO_DE_LIS  INNER JOIN STA11 (NOLOCK) ON STA11.COD_ARTICU = GVA17.COD_ARTICU  
LEFT JOIN (SELECT COD_ARTICU, DESCRIPCIO FROM STA11 WHERE USA_ESC = 'B') AS BASE ON  (CASE STA11.BASE WHEN '' THEN STA11.COD_ARTICU ELSE STA11.BASE END) = BASE.COD_ARTICU 
LEFT JOIN MEDIDA ON MEDIDA.ID_MEDIDA = STA11.ID_MEDIDA_STOCK 

WHERE 

STA11.PERFIL <> 'N'
 AND 
 GVA10.HABILITADA = 1 AND GVA10.NRO_DE_LIS IN ( '10' , '99' ) 


GROUP BY 
	STA11.COD_ARTICU , STA11.DESCRIPCIO , GVA17.PRECIO , GVA10.NRO_DE_LIS , GVA10.NOMBRE_LIS , GVA17.FECHA_MODI, STA11.PORC_UTILI
