ALTER TRIGGER TR_UPDATE_STA14_ON_CPA_OC_REMITO
ON CPA_OC_REMITO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @NCOMP_IN_S CHAR(14), @TCOMP_IN_S CHAR(4), @N_ORDEN_CO CHAR(14), @ID_SUCURSAL_DESTINO INT;

    -- Obtener los valores de la inserción reciente
    SELECT @NCOMP_IN_S = NCOMP_IN_S, @TCOMP_IN_S = TCOMP_IN_S, @N_ORDEN_CO = N_ORDEN_CO
    FROM inserted;

    -- Obtener el ID_SUCURSAL_DESTINO desde la tabla CPA35 usando el N_ORDEN_CO
    SELECT @ID_SUCURSAL_DESTINO = ID_SUCURSAL_DESTINO
    FROM CPA35
    WHERE N_ORDEN_CO = @N_ORDEN_CO;

    -- Actualizar el NRO_SUCURSAL_DESTINO en la tabla STA14 usando los valores obtenidos
    UPDATE STA14
    SET NRO_SUCURSAL_DESTINO_REMITO = @ID_SUCURSAL_DESTINO
		FROM STA14 JOIN VariablesGlobales VG ON
	VG.Valor = STA14.NCOMP_IN_S COLLATE Modern_Spanish_CI_AI
		WHERE TCOMP_IN_S = 'VS'
END;
